config/routes.rb
Rails.application.routes.draw do
  root "search_results#new"

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :trips

  resources :users do
    resources :messages
  end

  resources :users
  get '/user_searches' => 'search_results#user_index'

  get '/search_results' =>  'search_results#index'
  post '/search_results' => 'search_results#create'
  get '/save_search' =>  'search_results#new'
  post '/save_search' => 'search_results#save_result'

  get '/guides/search' => "guides#find_guides"
  resources :guides, only: [:index, :new]

  resources :search_results do
    get :autocomplete_location_city, :on => :collection
  end

end

app/models/search_result.rb
class SearchResult < ActiveRecord::Base
  belongs_to :user
  has_many :search_result_locations
  has_many :locations, through: :search_result_locations

  validates :budget, presence: true
  validates :start_at, presence: true
end

app/controllers/search_results_controller.rb
require 'momondo/client.rb'

class SearchResultsController < ApplicationController
  before_action :set_user_results, only: [:user_index]
  before_action :set_result, only: [:show]

  # autocomplete :location, :city, :full => true

  def autocomplete_location_city
    cities = Location.where("city ILIKE ?", "%#{params[:term]}%").pluck(:city)
    render :json => cities
  end

  def index
  end

  def new
    @search_result = SearchResult.new
    @ip = request.ip
    @user_location = Location.new
    @city = @user_location.geo_locate(@ip)
  end

  def create
    @search_result = SearchResult.new(search_result_params)
    airport_code = convert_city_to_airport(@search_result.current_city.downcase)
    @client = Momondo::Client.new
    @results = @client.where_to_go(leave_date: @search_result.start_at.to_s ,leave_from: airport_code, max_price: @search_result.budget)

    if current_user
      @search_result.user_id = current_user.id
    end

    if @search_result.save
      @results.each do |result|
        @converted_location_city = convert_airport_to_city(result.destination)
        @location = Location.find_by(city: @converted_location_city)
        @search_location = SearchResultLocation.new(location_id: @location.id, search_result_id: @search_result.id)
        @search_location.save
      end
     render "search_results/index"
    else
      redirect_to '/'
    end
  end

  def save_result
    @search = SearchResult.find(params[:search])
    @search.visible = true

    if @search.save
      redirect_to 'search_results/#{@search.id}'
    else
      redirect_to '/'
    end
  end

  private
  def set_user_results
    @results = current_user.search_results
  end

  def set_result
    @result = SearchResult.find(params[:id])
  end

  def search_result_params
   params.require(:search_result).permit(:current_city, :budget, :start_at, :end_at)
  end

  def convert_city_to_airport(current_city)#this method convert the city into airport code
   Location.find_by(city: current_city).airports.first.code
  end

  def convert_airport_to_city(code)
    if code != nil
    @destination = Airport.find_by(code: code).location.city
    end
  end
end

app/helpers/search_results_helper.rb
module SearchResultsHelper
  def convert_airport_to_city(code)
    if code != nil
    @destination = Airport.find_by(code: code).location.city
    end
  end

  def make_url(result)
    url = "blah"
  end

  def momondo_url(result)
    query = URI.encode_www_form({
                                  :"Search" => true,
                                  :"TripType" => "return",
                                  :"SegNo" => 2,
                                  :"SO0" => result.origin,
                                  :"SD0" => result.destination,
                                  :"SDP0" => result.depart_time,
                                  :"SO1" => result.destination,
                                  :"SD1" => result.origin,
                                  :"SDP1" => result.return_time,
                                  :"AD" => 1,
                                  :"rt" => true,
                                  :"Search" => true,
                                  :TripType => "return",
                                  :SegNo => 2,
                                  :SO0 => result.origin,
                                  :SD0 => result.destination,
                                  :SDP0 => result.depart_time,
                                  :SO1 => result.destination,
                                  :SD1 => result.origin,
                                  :SDP1 => result.return_time,
                                  :AD => 1,
                                  :TK => "ECO",
                                  :DO => false,
                                  :NA => false
                                })
    "http://www.momondo.com/multicity/?#{query}"
  end
end

app/views/search_results/_form.html.erb
<%= form_for @search_result do |f| %>
  <%= f.label "I want to leave from" %>
  <%= f.text_field :current_city, value: @city, include_blank: true, :"data-autocomplete-path" => autocomplete_location_city_search_results_path, id: 'current-city-text-field' %><br>
  <%= f.label "I have $" %>
  <%= f.text_field :budget %><br>
  <%= f.label "I'm leaving"%>
  <%= f.date_select :start_at %><br>

  <%= f.submit "Send me somewhere" %>
<% end %>

app/views/search_results/index.html.erb
<div class="standard_box">

  <% @results.each do |result| %>
    <div class="initial_results">
      <h1 class="title"><%= convert_airport_to_city(result.destination).capitalize %></h1>
      <h3>$<%= GoogCurrency.eur_to_usd(result.price).to_i%></h3>
      <%= image_tag('temp.jpg') %>

      <p>Leave <%= convert_airport_to_city(result.origin).capitalize %>
        <%= result.depart_time.month %>/<%= result.depart_time.day %>
        /<%= result.depart_time.year %>
        <br>
        Leave  <%= convert_airport_to_city(result.destination).capitalize %>
        <%= result.return_time.month %>/<%= result.return_time.day %>
        /<%= result.return_time.year %>
      </p><br>

      <%= form_for Trip.new do |f| %>
        <%= f.hidden_field :origin_id, value: Location.find_by(city: convert_airport_to_city(result.origin)).id %>
        <%= f.hidden_field :destination_id, value: Location.find_by(city: convert_airport_to_city(result.destination)).id %>
        <%= f.hidden_field :start_at, value: result.depart_time%>
        <%= f.hidden_field :end_at, value: result.return_time%>

        <%= f.submit "Save Trip" %>
            <br>
            <br>
            <br>
      <% end %>

      <span class="button "><%= link_to "Book Ticket", momondo_url(result), :target => "_blank" %></span>
    </div>
  <% end %>
</div>

<div class="sidebar">
  <% if current_user %>
    <h3><%= link_to "Save Search Results", save_search_path(search: @search_result.id), method: :post %></h3>
  <% else %>
    <h3> <%= link_to 'Log In', '/login' %> or <%= link_to 'Sign Up', new_user_path %><br>to save search results </h3>
  <%end%>
  <h3><%= link_to "New Search", new_search_result_path%></h3>
</div>

app/views/search_results/new.html.erb
<div class="standard_box">
  <%= render "search_results/form" %>
</div>

app/views/search_results/show.html.erb
<%= @result.current_city %>
<%= @result.budget %>

app/views/search_results/user_index.html.erb
<div class="standard_box">
  <% if @results.count != 0 %>
    <h1> Your Previous Searches </h1>
    <% @results.each do |result| %>
      $<%= result.budget %>
      From: <%= result.start_at %>
      <% result.locations.each do |location| %>
        <%= location.city %>
        <% end %>
      <br><br>
    <% end %>
  <% else %>
    <h2> You have no Searches! </h2>
  <%end%>
</div>