config/routes.rb
Rails.application.routes.draw do
  root "search_results#new"

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :trips

  resources :users do
    resources :messages
  end

  resources :users
  get '/user_searches' => 'search_results#user_index'

  get '/search_results' =>  'search_results#index'
  post '/search_results' => 'search_results#create'
  get '/save_search' =>  'search_results#new'
  post '/save_search' => 'search_results#save_result'

  get '/guides/search' => "guides#find_guides"
  resources :guides, only: [:index, :new]

  resources :search_results do
    get :autocomplete_location_city, :on => :collection
  end

end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  def index
    @guides = User.where(guide: true)
  end

  def new
    @guide = User.find(session[:user_id])
  end

  def find_guides
    @loc = Location.find_by(city: params[:city].downcase)
    @guides = @loc.guides
  end
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/views/guides/find_guides.html.erb
<div class="standard_box">
  <h1><%= @loc.city.capitalize %> Guides</h1>
  <% if @guides.length > 0 %>
    <% @guides.each do |guide| %>
      <h2><%= link_to guide.first_name, user_path(guide.id) %></h2><br>
      <p><%= guide.bio %></p>
    <% end %>
  <% else %>
  <h2>No guides yet for <%= @loc.city %></h2>
  <% end %>
</div>

app/views/guides/index.html.erb
<div class="standard_box">
  <br><br>
  <h1>Find a guide</h1>
  <%= form_tag guides_search_path, method: "get" do %>
  <%= label_tag(:city, "Search by city:") %>
  <%= text_field_tag(:city) %>
  <%= submit_tag("Search") %>
<% end %>
<br>
  <span class="button "><%= link_to "Become a guide", new_guide_path %></span>
</div>

app/views/guides/new.html.erb
<div class="standard_box">
<%= form_for @guide do |f| %>
  <%= f.label "Want to become a guide?" %>
  <%= f.check_box(:guide, {}, true) %>Yes!<br>
  <%= f.label "In which city ?"%>
  <%= f.text_field :location, value:"" %><br>

  <%= f.submit "Become a guide" %>
<% end %>
</div>